---
title: "Kelp Factors"
author: "Conner Smith"
date: "2/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(janitor)
library(cowplot)
library(plotly)
library(data.table)
library(lubridate)
library(tidyverse)
```

```{r}
# read in the first data sets

#This is regional and will not be continued past 2019, only using this to get the nitrate graph level and map kelp biomass across the region 
kelp_factors <- read_csv(here("data", "kelp_no3_waves.csv"))

#This is the more intricate data at the reef level based on diver surveys instead of the landsat images. 
kelp_abund <- read_csv(here('data', 'annual_kelp.csv'))

#Temperatur is also available at the site level. 
temp_big <- fread('https://pasta.lternet.edu/package/data/eml/knb-lter-sbc/13/26/d707a45a2cd6eee1d016d99844d537da')

# tempo should be compared to this other kelp abundance doc:
kelp_density <- read_csv(here('data', 'Annual_All_Species_Biomass_at_transect_20210108.csv'))

# This worked: Note: fread was much faster then read_csv

```
```{r}
kelp_abund_sub <- kelp_abund %>%
  clean_names() %>% 
  mutate(site = case_when(site == 'CARP' ~ 'Carpinteria',
                          site == 'NAPL' ~ 'Naples',
                          site == 'MOHK' ~ 'Mohawk',
                          site == 'IVEE' ~ 'Isla Vista',
                          site == 'AQUE' ~ 'Arroyo Quemado',
                          site == 'ABUR' ~ 'Arroyo Burro',
                          site == 'AHND' ~ 'Arroyo Hondo',
                          site == 'SCTW' ~ 'Santa Cruz - Harbor',
                          site == 'SCDI' ~ 'Santa Cruz - Diablo',
                          site == 'BULL' ~ 'Bulito',
                          site == 'GOLB' ~ 'Goleta Bay')) %>% 
  group_by(site) %>% 
  na_if(-99999) %>% 
  drop_na()

kelp_abund_summary <- kelp_abund_sub %>%
  select(site, fronds) %>% 
  group_by(site) %>% 
  slice(1:5) %>% 
  mutate(avg_fronds = mean(fronds)) %>% 
  arrange(-avg_fronds)
  
  
  
```


```{r}
# This is a standalone data for fronds at the reef level  

kelp_density_sub <- kelp_density %>%
  clean_names() %>% 
  mutate(site = case_when(site == 'CARP' ~ 'Carpinteria',
                          site == 'NAPL' ~ 'Naples',
                          site == 'MOHK' ~ 'Mohawk',
                          site == 'IVEE' ~ 'Isla Vista',
                          site == 'AQUE' ~ 'Arroyo Quemado',
                          site == 'ABUR' ~ 'Arroyo Burro',
                          site == 'AHND' ~ 'Arroyo Hondo',
                          site == 'SCTW' ~ 'Santa Cruz - Harbor',
                          site == 'SCDI' ~ 'Santa Cruz - Diablo',
                          site == 'BULL' ~ 'Bulito',
                          site == 'GOLB' ~ 'Goleta Bay')) %>% 
  filter(coarse_grouping == "GIANT KELP") %>%
  group_by(site, date) %>% 
  na_if(-99999) %>% 
  summarise(density=mean(density,na.rm=T)) %>% 
  ungroup()
  
#Subset for sumamry table on density
  
kelp_density_summary <- kelp_density_sub %>%
  mutate(year = year(date)) %>% 
  group_by(year,site) %>%
  summarise(density=mean(density,na.rm=T)) %>%
  ungroup()

kelp_density_year <- kelp_density_summary %>%
  group_by(site) %>% 
  summarise(density= round(mean(density,na.rm=T), 2)) %>% 
  arrange(-density)
  

# Now creating a subset of  the temperature data and creating a smaller csv for github 

temp_day_sub <- temp_big %>% 
  clean_names() %>%
  mutate(site = case_when(site == 'CARP' ~ 'Carpinteria',
                          site == 'NAPL' ~ 'Naples',
                          site == 'MOHK' ~ 'Mohawk',
                          site == 'IVEE' ~ 'Isla Vista',
                          site == 'AQUE' ~ 'Arroyo Quemado',
                          site == 'ABUR' ~ 'Arroyo Burro',
                          site == 'AHND' ~ 'Arroyo Hondo',
                          site == 'SCTW' ~ 'Santa Cruz - Harbor',
                          site == 'SCDI' ~ 'Santa Cruz - Diablo',
                          site == 'BULL' ~ 'Bulito',
                          site == 'GOLB' ~ 'Goleta Bay')) %>% 
  mutate(date = ymd(date_local)) %>% 
  mutate(as.Date(date)) %>%
  group_by(site, date) %>% 
  summarize(day_avg_temp = mean(temp_c))
  
write.csv(temp_day_sub, 'C:\\Users\\conne\\Documents\\ESM 244\\Shiny\\ESM244_SBC_LTER_Shiny\\data\\daily_avg_temp.csv', row.names = FALSE)

# Have the csv now for github, going to wrangle to get mongthly averages.
```


```{r}

# Now lets just  work with the subset 
temp_day_sub <- read_csv(here("data", "daily_avg_temp.csv"))

temp_coeff <- 3
#For a combined graph if we need one 

temp_plot <- 
  ggplot(data = temp_day_sub, aes(x = date, y = day_avg_temp)) +
  geom_smooth(color = "coral") +
  labs(y = "Average Temperature (Degrees Celsius)")
temp_plot

density_plot <- 
  ggplot(data = kelp_density_sub, aes(x = date, y = density)) +
  geom_col(color = "darkseagreen") +
  labs(y = "Average Density (Coverage Per Square Meter)")
density_plot
  

combined_plot <- 
ggplot() +
  geom_smooth(data = temp_month_sub, aes(x = date, y = month_avg_temp),
              color = "cadetblue3") +  
  geom_col(data = kelp_abund_sub, aes(x = date, y = density/temp_coeff),
           fill = "darkseagreen", alpha = 0.7) +
  scale_y_continuous(
    # Features of the first axis
    name = "Average Monthly Temperature (Degrees Celsius)",
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*temp_coeff, name = " Average Monthly Kelp Density (Fronds per meter squared)")
  ) +
  labs(title = "Kelp Density and Temperature by LTER Site Over Time") +
  theme_bw()
```




```{r}
# This takes data collected across CA and filters down fro SB site range 
# The range DOES NOT include islands sites 

kelp_factors_sub <- kelp_factors %>% 
  filter(site_id %in% c(267:298)) %>% 
  group_by(site_id, year)

kelp_biomass_plot <- ggplot(data = kelp_factors_sub, 
                       aes(x = year, y = kelp)) +
  geom_col(fill = "darkseagreen") +
  theme_minimal() +
  labs(title = "\nKelp Biomass Over Time\n", 
       x = "Year", y = "\nKelp Biomass (kg)\n")

no3_plot <- ggplot(data = kelp_factors_sub, 
                       aes(x = year, y = no3)) +
  geom_smooth(color = "coral") +
  theme_minimal() +
  labs(title = "\nNitrate Concentration Over Time\n", 
       x = "Year", y = "\nNitrate COncentration (uM/L)\n")
no3_plot

nitrate_kelp <- plot_grid (kelp_biomass_plot, no3_plot)
nitrate_kelp

# Now we will try to show these on the same plot with different y axes 

#First we need to estimate a scaling coefficient between the numbers, kelp biomass numbers generally 4 orders of magnitude larger (e.g. 10^7)

coeff <- 10^7
#This is the best scaling factor after trying a few 

combined_no3 <- ggplot(data = kelp_factors_sub, 
                       aes(x = year, y = no3)) +
  # now integrate the nitrogen curve with the kelp
  geom_smooth(color = "coral") + #now we need to scale the kelp axis  
  geom_col(aes(y = kelp/coeff), fill = "darkseagreen", alpha = 0.7) +
  scale_y_continuous(
    # Features of the first axis
    name = "NO3 Concentration (uM/L)",
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*coeff, name=" Kelp Biomass (kg)")
  ) +
  theme_bw()


# Table summary of nitrogen and temp
n_summary <- kelp_factors_sub %>% 
  group_by(year) %>% 
  summarize(no3 = mean(no3, na.rm = T))

t_summary <- temp_day_sub %>% 
  mutate(year = year(date)) %>% 
  group_by(year) %>% 
  summarize(year_avg_temp = mean(day_avg_temp))

n_t_join <- 
  inner_join(n_summary, t_summary, by = "year")
```

```{r}
# Creating anothe rgraph for wave height 

combined_waves <- ggplot(data = kelp_factors_sub, 
                       aes(x = year, y = waves)) +
  # now integrate the wave curve with the kelp
  geom_smooth(color = "cadetblue3") + #now we need to scale the kelp axis  
  geom_col(aes(y = kelp/coeff), fill = "darkseagreen", alpha = 0.7) +
  scale_y_continuous(
    # Features of the first axis
    name = "Average Wave Height (m)",
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*coeff, name=" Kelp Biomass (kg)")
  ) +
  theme_bw()
ggplotly(combined_waves)



```


